version: "3.8"

services:
  inventory-service-mongodb:
    container_name: inventory-service-mongodb
    image: mongo:5.0.9
    restart: always
    env_file: ./.env
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_ROOT_USER_NAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_ROOT_USER_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DB_NAME
    ports:
      - "27017:27017"