version: "3.8"

services:
  inventory-service-mongodb:
    container_name: inventory-service-mongodb
    image: mongo:5.0.9
    restart: always
    env_file: ./.env
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_ROOT_USER_NAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_ROOT_USER_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DB_NAME
    ports:
      - "27017:27017"

  inventory-service:
    container_name: inventory-service
    build: ./app
    working_dir: /app
    restart: on-failure
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.data.mongodb.authentication-database": "admin",
          "spring.data.mongodb.username": "$MONGODB_ROOT_USER_NAME",
          "spring.data.mongodb.password": "$MONGODB_ROOT_USER_PASSWORD",
          "spring.data.mongodb.database": "$MONGODB_DB_NAME",
          "spring.data.mongodb.host": "localhost",
          "spring.data.mongodb.port": 27017
        }'
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    command: mvn clean spring-boot:run
    depends_on:
      - inventory-service-mongodb
